// routes/gameRoutes.js
const express = require('express');
const router = express.Router();

// Array of word sets
const wordSets = [
    ['APPLE', 'EARLY', 'SUNNY', 'ATOMS'],
    ['MAJOR', 'ROUTE', 'CRUDE', 'MAGIC'],
    ['WIDTH', 'HOPED', 'GRAND', 'WRONG'],
    ['GLOVE', 'EMPTY', 'FUNNY', 'GRIEF'],
    ['SHELL', 'LIVER', 'RULER', 'SUGAR'],
    ['SHIRT', 'THICK', 'WRECK', 'SCREW'],
    ['SOUND', 'DEATH', 'FRESH', 'SHELF'],
    ['COVER', 'RATIO', 'RADIO', 'CLEAR'],
    ['SCOPE', 'ENTER', 'FLOUR', 'STAFF'],
    ['HAPPY', 'YOUNG', 'AMONG', 'HYENA'],
    ['STIFF', 'FORCE', 'TRADE', 'SIGHT'],
    ['PLAIN', 'NIGHT', 'FLINT', 'PROOF'],
    ['OPIUM', 'MODEL', 'RIVAL', 'OFFER'],
    ['ALPHA', 'ADDED', 'DELTA', 'AHEAD'],
    ['ARENA', 'AHEAD', 'DRAMA', 'ADDED'],
    ['ADDED', 'DELTA', 'ALPHA', 'ARENA'],
    ['AHEAD', 'DRAMA', 'ARENA', 'ALPHA'],
    ['AIMED', 'DATED', 'DRIED', 'AMEND'],
    ['AMEND', 'DRIED', 'DATED', 'AIMED'],
    ['ARMED', 'DANCE', 'EXTRA', 'ABOVE'],
    ['ASKED', 'DENSE', 'ENDED', 'ABUSE'],
    ['AVOID', 'DODGE', 'EAGLE', 'ACUTE'],
    ['AWARD', 'DRIVE', 'ELITE', 'ADOBE'],
    ['ABOVE', 'ENDED', 'DANCE', 'ARMED'],
    ['ABUSE', 'EAGLE', 'ENDIF', 'AGREE'],
    ['ACUTE', 'ELITE', 'EARTH', 'ALIKE'],
    ['ADOBE', 'EMAIL', 'LOGIC', 'ANGEL'],
    ['AGREE', 'EQUAL', 'LYRIC', 'APRIL'],
    ['ALIKE', 'EXCEL', 'LIKED', 'AWFUL'],
    ['ALIVE', 'EPSON', 'NAKED', 'ADMIN'],
    ['ALONE', 'ELDER', 'REHAB', 'ACTOR'],
    ['ANGLE', 'ENTER', 'RAPID', 'AFTER'],
    ['ANIME', 'ERROR', 'RATED', 'ALTER'],
    ['APPLE', 'EDGES', 'SANTA', 'ACIDS'],
    ['ARGUE', 'EUROS', 'SCUBA', 'ACRES'],
    ['ARISE', 'EXAMS', 'SIGMA', 'ALIAS'],
    ['ASIDE', 'EIGHT', 'THUMB', 'ABOUT'],
    ['AWARE', 'ELECT', 'TOPIC', 'ADMIT'],
    ['AGING', 'GRAND', 'DENSE', 'ASKED'],
    ['ALONG', 'GUARD', 'DODGE', 'AVOID'],
    ['AMONG', 'GUILD', 'DRIVE', 'AWARD'],
    ['ANGEL', 'LANCE', 'EBOOK', 'ALIVE'],
    ['APRIL', 'LARGE', 'EMAIL', 'ALONE'],
    ['AWFUL', 'LEASE', 'EQUAL', 'ANGLE'],
    ['ALARM', 'MAPLE', 'EXCEL', 'ANIME'],
    ['ALBUM', 'MAYBE', 'EPSON', 'APPLE'],
    ['ADMIN', 'NERVE', 'ELDER', 'ARGUE'],
    ['AGAIN', 'NOBLE', 'ENTER', 'ARISE'],
    ['ALIEN', 'NOISE', 'ERROR', 'ASIDE'],
    ['ALIGN', 'NURSE', 'EDGES', 'AWARE'],
    ['ASIAN', 'NYLON', 'NAMED', 'AGAIN'],
    ['AUDIO', 'OCEAN', 'NOTED', 'ALIEN'],
    ['ACTOR', 'REALM', 'MANGA', 'ALARM'],
    ['AFTER', 'RADIO', 'OMEGA', 'AUDIO'],
    ['ALTER', 'RADAR', 'ROUND', 'AMBER'],
    ['AMBER', 'REFER', 'RULED', 'ANGER'],
    ['ANGER', 'RIDER', 'RAISE', 'ARMOR'],
    ['ARMOR', 'RACES', 'SONIC', 'AREAS'],
    ['ACIDS', 'SWING', 'GAMMA', 'AGING'],
    ['ACRES', 'SERUM', 'MEDIA', 'ALBUM'],
    ['ALIAS', 'SALON', 'NERVE', 'ALIGN'],
    ['AREAS', 'SATIN', 'NOBLE', 'ASIAN'],
    ['ATLAS', 'SALES', 'SALAD', 'AUTOS'],
    ['AUTOS', 'SAVES', 'SAVED', 'ATLAS'],
    ['ABOUT', 'THING', 'GONNA', 'ALONG'],
    ['ADMIT', 'THONG', 'GOTTA', 'AMONG'],
    ['ADOPT', 'THEFT', 'TOXIC', 'ADULT'],
    ['ADULT', 'TIGHT', 'THIRD', 'ADOPT'],
    ['AGENT', 'TRACT', 'TIRED', 'ALERT'],
    ['ALERT', 'TREAT', 'TREND', 'AGENT'],
    ['APART', 'TROUT', 'TRIED', 'ASSET'],
    ['ASSET', 'TRUST', 'TABLE', 'APART'],
    ['AUDIT', 'THROW', 'WANNA', 'ALLOW'],
    ['ALLOW', 'WHEAT', 'TASTE', 'AUDIT'],
    ['ARROW', 'WORRY', 'YIELD', 'ALLOY'],
    ['BASIC', 'CHILD', 'DROVE', 'BASED'],
    ['BASED', 'DROVE', 'EUROS', 'BADGE'],
    ['BLEND', 'DEBUG', 'GRAND', 'BEING'],
    ['BLIND', 'DOING', 'GUARD', 'BRING'],
    ['BLOND', 'DEATH', 'HEARD', 'BATCH'],
    ['BLOOD', 'DEPTH', 'HIRED', 'BEACH'],
    ['BOARD', 'DUTCH', 'HOPED', 'BENCH'],
    ['BORED', 'DRINK', 'KARMA', 'BLACK'],
    ['BOUND', 'DRUNK', 'KNIFE', 'BLANK'],
    ['BOXED', 'DREAM', 'MAGIC', 'BLOOM'],
    ['BRAND', 'DOZEN', 'NOISE', 'BACON'],
    ['BREAD', 'DRAIN', 'NURSE', 'BASIN'],
    ['BREED', 'DRAWN', 'NORTH', 'BEGAN'],
    ['BROAD', 'DISCO', 'OPERA', 'BINGO'],
    ['BUILD', 'DECOR', 'RANGE', 'BAKER'],
    ['BADGE', 'ENDIF', 'FACED', 'BRIEF'],
    ['BIBLE', 'EARTH', 'HENCE', 'BIRTH'],
    ['BLADE', 'EBOOK', 'KNOCK', 'BLINK'],
    ['BLAME', 'EVENT', 'THEME', 'BEAST'],
    ['BRAKE', 'EXACT', 'THERE', 'BLAST'],
    ['BRAVE', 'EXIST', 'THESE', 'BOOST'],
    ['BRIDE', 'EARLY', 'YOUNG', 'BADLY'],
    ['BROKE', 'EBONY', 'YOUTH', 'BELLY'],
    ['BRIEF', 'FACED', 'DEBUG', 'BLEND'],
    ['BEING', 'GAUGE', 'EXAMS', 'BIBLE'],
    ['BRING', 'GENRE', 'EIGHT', 'BLADE'],
    ['BATCH', 'HEARD', 'DOING', 'BLIND'],
    ['BEACH', 'HIRED', 'DYING', 'BLOND'],
    ['BENCH', 'HOPED', 'DEATH', 'BLOOD'],
    ['BIRTH', 'HENCE', 'ELECT', 'BLAME'],
    ['BOOTH', 'HORSE', 'EVENT', 'BRAKE'],
    ['BRUSH', 'HOUSE', 'EXACT', 'BRAVE'],
    ['BUNCH', 'HEATH', 'HORSE', 'BOOTH'],
    ['BLACK', 'KNIFE', 'EXIST', 'BRIDE'],
    ['BLANK', 'KNOCK', 'KNOWN', 'BLOCK'],
    ['BLINK', 'KNOWN', 'NAVAL', 'BEGIN'],
    ['BLOCK', 'KEEPS', 'SIZED', 'BALLS'],
    ['BREAK', 'KILLS', 'SOLID', 'BANDS'],
    ['BRICK', 'KINDS', 'SOUND', 'BANKS'],
    ['BROOK', 'KINGS', 'SPEED', 'BASES'],
    ['BLOOM', 'MAGIC', 'CLIMB', 'BASIC'],
    ['BACON', 'NAKED', 'DEPTH', 'BOARD'],
    ['BASIN', 'NAMED', 'DUTCH', 'BORED'],
    ['BEGAN', 'NOTED', 'DRINK', 'BOUND'],
    ['BEGIN', 'NORTH', 'HOUSE', 'BRUSH'],
    ['BEGUN', 'NEVER', 'RIDGE', 'BUYER'],
    ['BRAIN', 'NAILS', 'SPEND', 'BASIS'],
    ['BROWN', 'NAMES', 'SQUAD', 'BATHS'],
    ['BINGO', 'OWNED', 'DRUNK', 'BOXED'],
    ['BAKER', 'RAPID', 'DEVIL', 'BRAND'],
    ['BUYER', 'RATED', 'DRILL', 'BREAD'],
    ['BALLS', 'SALAD', 'DREAM', 'BREED'],
    ['BANDS', 'SAVED', 'DOZEN', 'BROAD'],
    ['BANKS', 'SIZED', 'DRAIN', 'BUILD'],
    ['BASES', 'SAUCE', 'EARLY', 'BROKE'],
    ['BASIS', 'SARAH', 'HEATH', 'BUNCH'],
    ['BATHS', 'SHARK', 'KEEPS', 'BREAK'],
    ['BEADS', 'SHOCK', 'KILLS', 'BRICK'],
    ['BEANS', 'SPANK', 'KINDS', 'BROOK'],
    ['BEARS', 'SEVEN', 'NOVEL', 'BEGUN'],
    ['BEATS', 'SHOWN', 'NYLON', 'BRAIN'],
    ['BELTS', 'SEATS', 'STAND', 'BEADS'],
    ['BIKES', 'SEEDS', 'STOOD', 'BEANS'],
    ['BILLS', 'SEEKS', 'SWORD', 'BEARS'],
    ['BIRDS', 'SEEMS', 'SAUCE', 'BEATS'],
    ['BLESS', 'SELLS', 'SCALE', 'BELTS'],
    ['BLOGS', 'SENDS', 'SCENE', 'BIKES'],
    ['BLUES', 'SHIPS', 'SCOPE', 'BILLS'],
    ['BOATS', 'SHOES', 'SCORE', 'BIRDS'],
    ['BONDS', 'SHOPS', 'SENSE', 'BLESS'],
    ['BONES', 'SHOTS', 'SERVE', 'BLOGS'],
    ['BONUS', 'SHOWS', 'SHADE', 'BLUES'],
    ['BOOKS', 'SIDES', 'SHAKE', 'BOATS'],
    ['BOOTS', 'SIGNS', 'SHAME', 'BONDS'],
    ['BOXES', 'SITES', 'SHAPE', 'BONES'],
    ['BRASS', 'SIZES', 'SHARE', 'BONUS'],
    ['BUCKS', 'SKINS', 'SHINE', 'BOOKS'],
    ['BURNS', 'SLOTS', 'SHORE', 'BOOTS'],
    ['BUSES', 'SOCKS', 'SINCE', 'BOXES'],
    ['BYTES', 'SONGS', 'SLAVE', 'BRASS'],
    ['BEAST', 'TAKEN', 'NEVER', 'BROWN'],
    ['BLAST', 'TAKES', 'SLIDE', 'BUCKS'],
    ['BOOST', 'TALES', 'SLOPE', 'BURNS'],
    ['BUILT', 'TALKS', 'SMILE', 'BUSES'],
    ['BURST', 'TANKS', 'SMOKE', 'BYTES'],
    ['BELOW', 'WORST', 'THOSE', 'BUILT'],
    ['BADLY', 'YACHT', 'THREE', 'BURST'],
    ['CLIMB', 'BASIC', 'CIVIC', 'COMIC'],
    ['CIVIC', 'COMIC', 'CHILD', 'CUBIC'],
    ['COMIC', 'CUBIC', 'CITED', 'CIVIC'],
    ['CUBIC', 'CITED', 'DRAWN', 'CHILD'],
    ['CHILD', 'DEVIL', 'LINED', 'CAMEL'],
    ['CITED', 'DRILL', 'LIVED', 'CANAL'],
    ['CLOUD', 'DONOR', 'ROUTE', 'CEDAR'],
    ['COULD', 'DOVER', 'RANCH', 'CHAIR'],
    ['CROWD', 'DRYER', 'REACH', 'CHOIR'],
    ['CABLE', 'EMPTY', 'YARDS', 'CANDY'],
    ['CACHE', 'ENEMY', 'YEARS', 'CARRY'],
    ['CAUSE', 'ENJOY', 'YOURS', 'CRAZY'],
    ['CHIEF', 'FIELD', 'DISCO', 'CITED'],
    ['CLIFF', 'FILED', 'DECOR', 'CLOUD'],
    ['CATCH', 'HOTEL', 'LOVED', 'CAROL'],
    ['CLOTH', 'HAVEN', 'NEWER', 'CABIN'],
    ['COACH', 'HUMAN', 'NAILS', 'CANON'],
    ['CRASH', 'HELLO', 'OWNED', 'CARGO'],
    ['CHECK', 'KNOWS', 'SNAKE', 'CAKES'],
    ['CAMEL', 'LIKED', 'DONOR', 'COULD'],
    ['CANAL', 'LINED', 'DOVER', 'CROWD'],
    ['CAROL', 'LEAVE', 'EBONY', 'CABLE'],
    ['CIVIL', 'LODGE', 'EMPTY', 'CACHE'],
    ['CORAL', 'LOOSE', 'ENEMY', 'CAUSE'],
    ['CHARM', 'MERGE', 'ENJOY', 'CHASE'],
    ['CLAIM', 'MOUSE', 'ENTRY', 'CHOSE'],
    ['CREAM', 'MOVIE', 'ESSAY', 'CLONE'],
    ['CABIN', 'NAVAL', 'LANCE', 'CIVIL'],
    ['CANON', 'NOVEL', 'LARGE', 'CORAL'],
    ['CHAIN', 'NEWER', 'ROUGH', 'CLEAR'],
    ['CLEAN', 'NEEDS', 'SOLVE', 'CALLS'],
    ['COLON', 'NODES', 'SPACE', 'CAMPS'],
    ['CROWN', 'NOTES', 'SPARE', 'CARDS'],
    ['CARGO', 'OLIVE', 'EVERY', 'CLOSE'],
    ['COMBO', 'OFTEN', 'NAMES', 'CHAIN'],
    ['CONDO', 'ONION', 'NEEDS', 'CLEAN'],
    ['CONGO', 'ORGAN', 'NODES', 'COLON'],
    ['CHEAP', 'PROOF', 'FIELD', 'CHIEF'],
    ['CEDAR', 'REHAB', 'BASIC', 'CLIMB'],
    ['CHAIR', 'RANCH', 'HOTEL', 'CATCH'],
    ['CHOIR', 'REACH', 'HAVEN', 'CLOTH'],
    ['CLEAR', 'ROUGH', 'HUMAN', 'COACH'],
    ['COLOR', 'RATIO', 'OLIVE', 'COMBO'],
    ['COVER', 'RETRO', 'OXIDE', 'CONDO'],
    ['CYBER', 'RIVER', 'REBEL', 'COLOR'],
    ['CAKES', 'SHELF', 'FILED', 'CLIFF'],
    ['CALLS', 'SIXTH', 'HELLO', 'CRASH'],
    ['CAMPS', 'SPEAK', 'KINGS', 'CHECK'],
    ['CARDS', 'STACK', 'KNOWS', 'CHICK'],
    ['CASES', 'STICK', 'KITTY', 'CLERK'],
    ['CELLS', 'SPERM', 'MUSIC', 'CHARM'],
    ['CENTS', 'STEAM', 'MIXED', 'CLAIM'],
    ['CHAOS', 'STORM', 'MOVED', 'CREAM'],
    ['CHESS', 'SCOOP', 'PASTA', 'CHEAP'],
    ['CHIPS', 'SAFER', 'ROYAL', 'COVER'],
    ['CLASS', 'SAVER', 'RURAL', 'CYBER'],
    ['CLIPS', 'SORTS', 'SPICE', 'CASES'],
    ['CLUBS', 'SOULS', 'SPINE', 'CELLS'],
    ['CODES', 'SPIES', 'SPOKE', 'CENTS'],
    ['COINS', 'SPOTS', 'STAGE', 'CHAOS'],
    ['COMES', 'STARS', 'STATE', 'CHESS'],
    ['CORPS', 'STATS', 'STONE', 'CHIPS'],
    ['COSTS', 'STEPS', 'STORE', 'CLASS'],
    ['CRAPS', 'STOPS', 'STYLE', 'CLIPS'],
    ['CROPS', 'SUCKS', 'SUITE', 'CLUBS'],
    ['CROSS', 'SUITS', 'SURGE', 'CODES'],
    ['CHART', 'TOKEN', 'NOTES', 'CROWN'],
    ['CHEAT', 'TURBO', 'OZONE', 'CONGO'],
    ['CHEST', 'TAPES', 'SHELF', 'COINS'],
    ['COAST', 'TASKS', 'STAFF', 'COMES'],
    ['COUNT', 'TAXES', 'STUFF', 'CORPS'],
    ['COURT', 'TEAMS', 'SWING', 'COSTS'],
    ['CRAFT', 'TEARS', 'SARAH', 'CRAPS'],
    ['CREST', 'TEENS', 'SIXTH', 'CROPS'],
    ['CANDY', 'YARDS', 'SOUTH', 'CROSS'],
    ['CARRY', 'YEAST', 'TITLE', 'CHART'],
    ['DELTA', 'ALPHA', 'ADDED', 'DRAMA'],
    ['DRAMA', 'ARENA', 'AHEAD', 'DELTA'],
    ['DATED', 'DYING', 'GUILD', 'DEBUG'],
    ['DRIED', 'DATES', 'SHARK', 'DEALS'],
    ['DANCE', 'ENTRY', 'YACHT', 'DAILY'],
    ['DENSE', 'ESSAY', 'YEAST', 'DAIRY'],
    ['DEBUG', 'GOING', 'GAUGE', 'DOING'],
    ['DOING', 'GRAPH', 'HONOR', 'DEATH'],
    ['DYING', 'GRILL', 'LEASE', 'DEVIL'],
    ['DEATH', 'HONOR', 'REALM', 'DECOR'],
    ['DEPTH', 'HUMOR', 'RADIO', 'DONOR'],
    ['DUTCH', 'HANDS', 'SHOCK', 'DATES'],
    ['DEVIL', 'LIVED', 'DRYER', 'DATED'],
    ['DRILL', 'LOVED', 'DATES', 'DRIED'],
    ['DREAM', 'MARCH', 'HUMOR', 'DEPTH'],
    ['DOZEN', 'NIGHT', 'TRACE', 'DEALT'],
    ['DISCO', 'OCCUR', 'RATIO', 'DOVER'],
    ['DECOR', 'REBEL', 'LEAVE', 'DRILL'],
    ['DONOR', 'ROGER', 'RETRO', 'DRYER'],
    ['DOVER', 'RACKS', 'SPANK', 'DISCS'],
    ['DRYER', 'RANKS', 'SPEAK', 'DISKS'],
    ['DATES', 'SOUTH', 'HANDS', 'DUTCH'],
    ['DEALS', 'SWISS', 'STACK', 'DOLLS'],
    ['DISCS', 'SAINT', 'TRADE', 'DEBUT'],
    ['DISKS', 'SCOUT', 'TRIBE', 'DEPOT'],
    ['DOLLS', 'SHAFT', 'TWICE', 'DIGIT'],
    ['DOORS', 'SHEET', 'THING', 'DOUBT'],
    ['DRAWS', 'SHIFT', 'THONG', 'DRAFT'],
    ['DEALT', 'TRAIN', 'NIGHT', 'DOZEN'],
    ['DEBUT', 'TELLS', 'STICK', 'DOORS'],
    ['DEPOT', 'TERMS', 'STOCK', 'DRAWS'],
    ['DIGIT', 'TESTS', 'STUCK', 'DRESS'],
    ['DOUBT', 'TEXTS', 'SHALL', 'DROPS'],
    ['DRAFT', 'TILES', 'SHELL', 'DRUGS'],
    ['DAILY', 'YOUNG', 'GENRE', 'DYING'],
    ['DAIRY', 'YEARS', 'SKILL', 'DRUMS'],
    ['EXTRA', 'AIMED', 'DEALS', 'ENDED'],
    ['ENDED', 'DEALS', 'SMALL', 'EDGES'],
    ['ENDIF', 'FAITH', 'HEADS', 'EARTH'],
    ['EARTH', 'HEADS', 'SMELL', 'EUROS'],
    ['EBOOK', 'KARMA', 'AIMED', 'EXTRA'],
    ['EMAIL', 'LABEL', 'LODGE', 'EQUAL'],
    ['EQUAL', 'LEGAL', 'LOOSE', 'EMAIL'],
    ['EXCEL', 'LADEN', 'NASTY', 'EPSON'],
    ['ELDER', 'ROYAL', 'LYING', 'EXCEL'],
    ['ENTER', 'ROVER', 'RADAR', 'ELDER'],
    ['ERROR', 'RATES', 'SPELL', 'EXAMS'],
    ['EDGES', 'STAFF', 'FIRED', 'ENDIF'],
    ['EUROS', 'SHEER', 'REFER', 'ENTER'],
    ['EXAMS', 'SOLAR', 'RIDER', 'ERROR'],
    ['EIGHT', 'TWIST', 'TEACH', 'ELECT'],
    ['FACED', 'DISCS', 'STEAL', 'FACES'],
    ['FIELD', 'DISKS', 'STEEL', 'FACTS'],
    ['FILED', 'DOLLS', 'STILL', 'FAILS'],
    ['FIRED', 'DOORS', 'SERUM', 'FALLS'],
    ['FIXED', 'DRAWS', 'SPERM', 'FARES'],
    ['FLOOD', 'DRESS', 'STEAM', 'FARMS'],
    ['FLUID', 'DROPS', 'STORM', 'FEARS'],
    ['FOUND', 'DRUGS', 'SALON', 'FEEDS'],
    ['FRAUD', 'DRUMS', 'SATIN', 'FEELS'],
    ['FAITH', 'HELPS', 'SEVEN', 'FILES'],
    ['FIFTH', 'HERBS', 'SHOWN', 'FILMS'],
    ['FLASH', 'HIGHS', 'SCOOP', 'FINDS'],
    ['FLESH', 'HILLS', 'SETUP', 'FIRES'],
    ['FLUSH', 'HINTS', 'SHARP', 'FIRMS'],
    ['FORTH', 'HOLDS', 'SHEEP', 'FIXES'],
    ['FRESH', 'HOLES', 'SLEEP', 'FLAGS'],
    ['FATAL', 'LAUGH', 'HELPS', 'FAITH'],
    ['FINAL', 'LUNCH', 'HERBS', 'FIFTH'],
    ['FOCAL', 'LEVEL', 'LAUGH', 'FATAL'],
    ['FORUM', 'MIXED', 'DISCS', 'FACED'],
    ['FAVOR', 'ROUND', 'DISKS', 'FIELD'],
    ['FEVER', 'RULED', 'DOLLS', 'FILED'],
    ['FEWER', 'RURAL', 'LUNCH', 'FINAL'],
    ['FIBER', 'READS', 'STAMP', 'FLOWS'],
    ['FLOOR', 'RIDES', 'STRAP', 'FOCUS'],
    ['FLOUR', 'RINGS', 'STRIP', 'FOLKS'],
    ['FLYER', 'RISKS', 'SAFER', 'FONTS'],
    ['FACES', 'SOLID', 'DOORS', 'FIRED'],
    ['FACTS', 'SOUND', 'DRAWS', 'FIXED'],
    ['FAILS', 'SPEED', 'DRESS', 'FLOOD'],
    ['FALLS', 'SPEND', 'DROPS', 'FLUID'],
    ['FARES', 'SQUAD', 'DRUGS', 'FOUND'],
    ['FARMS', 'STAND', 'DRUMS', 'FRAUD'],
    ['FEARS', 'SHALL', 'LABEL', 'FOCAL'],
    ['FEEDS', 'SUGAR', 'RIVER', 'FAVOR'],
    ['FEELS', 'SUPER', 'ROGER', 'FEVER'],
    ['FILES', 'SHIRT', 'TEETH', 'FAULT'],
    ['FILMS', 'SHOOT', 'TOOTH', 'FIGHT'],
    ['FINDS', 'SHORT', 'TOUCH', 'FIRST'],
    ['FIRES', 'SIGHT', 'TOUGH', 'FLEET'],
    ['FIRMS', 'SKIRT', 'TRASH', 'FLOAT'],
    ['FIXES', 'SMART', 'TRUTH', 'FRONT'],
    ['FLAGS', 'SPENT', 'THANK', 'FROST'],
    ['FLOWS', 'SPLIT', 'THICK', 'FRUIT'],
    ['FAULT', 'TEACH', 'HIGHS', 'FLASH'],
    ['FIGHT', 'TEETH', 'HILLS', 'FLESH'],
    ['FIRST', 'TOOTH', 'HINTS', 'FLUSH'],
    ['FLEET', 'TOUCH', 'HOLDS', 'FORTH'],
    ['FLOAT', 'TOUGH', 'HOLES', 'FRESH'],
    ['FRONT', 'THEIR', 'ROVER', 'FEWER'],
    ['FROST', 'TIGER', 'RACES', 'FIBER'],
    ['FRUIT', 'TIMER', 'RACKS', 'FLOOR'],
    ['FAIRY', 'YOURS', 'SAVER', 'FOODS'],
    ['GAMMA', 'AMEND', 'DEALT', 'GRAND'],
    ['GONNA', 'ARMED', 'DEBUT', 'GUARD'],
    ['GOTTA', 'ASKED', 'DEPOT', 'GUILD'],
    ['GRAND', 'DEALT', 'THINK', 'GHOST'],
    ['GUARD', 'DEBUT', 'TRACK', 'GIANT'],
    ['GUILD', 'DEPOT', 'TRICK', 'GRANT'],
    ['GAUGE', 'EXTRA', 'AMEND', 'GAMMA'],
    ['GOING', 'GAMMA', 'ARMED', 'GONNA'],
    ['GRAPH', 'HOMES', 'SHEER', 'GAINS'],
    ['GRILL', 'LYING', 'GLOBE', 'GOING'],
    ['GROUP', 'PASTA', 'ASKED', 'GOTTA'],
    ['GAINS', 'SHELL', 'LEGAL', 'GRILL'],
    ['GAMES', 'SETUP', 'PIZZA', 'GROUP'],
    ['GATES', 'SPORT', 'TRUCK', 'GREAT'],
    ['GENES', 'START', 'TRUNK', 'GUEST'],
    ['GHOST', 'TRASH', 'HOMES', 'GRAPH'],
    ['GIANT', 'TIMES', 'SOLAR', 'GAMES'],
    ['GRANT', 'TIRES', 'SUGAR', 'GATES'],
    ['GREAT', 'TONES', 'SUPER', 'GENES'],
    ['GUEST', 'TOOLS', 'SALES', 'GIFTS'],
    ['HEARD', 'DIGIT', 'TOTAL', 'HEART'],
    ['HEATH', 'HOPES', 'SAVES', 'HANDS'],
    ['HOTEL', 'LATIN', 'NEWLY', 'HAVEN'],
    ['HELLO', 'OFFER', 'RANKS', 'HONOR'],
    ['HONOR', 'ROADS', 'SEATS', 'HEADS'],
    ['HUMOR', 'ROCKS', 'SEEDS', 'HELPS'],
    ['HANDS', 'STOOD', 'DIGIT', 'HEARD'],
    ['HEADS', 'SWORD', 'DOUBT', 'HIRED'],
    ['HELPS', 'SKILL', 'LEVEL', 'HOTEL'],
    ['HEART', 'THIRD', 'DRAFT', 'HOPED'],
    ['HINDU', 'UNDER', 'RATES', 'HUMOR'],
    ['HAIRY', 'YOUTH', 'HOPES', 'HEATH'],
    ['IRISH', 'HOSTS', 'SEEKS', 'ICONS'],
    ['IDEAL', 'LOCAL', 'LADEN', 'INTEL'],
    ['INTEL', 'LABOR', 'READS', 'INNER'],
    ['ISLAM', 'MATCH', 'HOSTS', 'IRISH'],
    ['INTRO', 'OLDER', 'RIDES', 'INTER'],
    ['INNER', 'ROLES', 'SEEMS', 'IDEAS'],
    ['INTER', 'ROLLS', 'SELLS', 'ITEMS'],
    ['ICONS', 'SMALL', 'LOCAL', 'IDEAL'],
    ['IDEAS', 'SWEET', 'TRAIL', 'INPUT'],
    ['JEWEL', 'LAKES', 'SENDS', 'JEANS'],
    ['JEANS', 'SMELL', 'LATIN', 'JEWEL'],
    ['JOINS', 'SWIFT', 'TRIAL', 'JOINT'],
    ['JOINT', 'TOURS', 'SHIPS', 'JOINS'],
    ['KARMA', 'ACIDS', 'SHOES', 'KEEPS'],
    ['KEEPS', 'SANTA', 'AVOID', 'KARMA'],
    ['LOGIC', 'CIVIC', 'COMIC', 'LYRIC'],
    ['LYRIC', 'CLOUD', 'DAILY', 'LIKED'],
    ['LIKED', 'DOUBT', 'TAKEN', 'LEAST'],
    ['LINED', 'DRAFT', 'TOKEN', 'LIGHT'],
    ['LYING', 'GAINS', 'SHOPS', 'LAKES'],
    ['LAUGH', 'HOURS', 'SHOTS', 'LAMPS'],
    ['LUNCH', 'HEART', 'TRAIN', 'LIMIT'],
    ['LABEL', 'LYRIC', 'CUBIC', 'LOGIC'],
    ['LEGAL', 'LASER', 'RINGS', 'LABOR'],
    ['LEVEL', 'LATER', 'RISKS', 'LASER'],
    ['LOCAL', 'LAYER', 'ROADS', 'LATER'],
    ['LABOR', 'ROOMS', 'SHOWS', 'LANDS'],
    ['LASER', 'ROOTS', 'SIDES', 'LANES'],
    ['LATER', 'ROSES', 'SIGNS', 'LEADS'],
    ['LAYER', 'RULES', 'SITES', 'LIKES'],
    ['LAKES', 'SPELL', 'LEARN', 'LABEL'],
    ['LAMPS', 'STEAL', 'LEMON', 'LEGAL'],
    ['LANDS', 'STEEL', 'LOGIN', 'LEVEL'],
    ['LANES', 'STILL', 'LABOR', 'LOCAL'],
    ['LEAST', 'TIRED', 'DAIRY', 'LINED'],
    ['LIGHT', 'TREND', 'DAISY', 'LIVED'],
    ['LIMIT', 'TRIED', 'DELAY', 'LOVED'],
    ['MANGA', 'AVOID', 'DERBY', 'MIXED'],
    ['MEDIA', 'AWARD', 'DIARY', 'MOVED'],
    ['MAGIC', 'CATCH', 'HOURS', 'MARCH'],
    ['MUSIC', 'CLOTH', 'HEART', 'MATCH'],
    ['MULTI', 'IRISH', 'HINDU', 'MONTH'],
    ['MEDAL', 'LOGIC', 'CLOUD', 'MAGIC'],
    ['METAL', 'LIVER', 'ROCKS', 'MAJOR'],
    ['MODEL', 'LOVER', 'ROLES', 'MAKER'],
    ['MORAL', 'LOWER', 'ROLLS', 'MANOR'],
    ['MOTEL', 'LAMPS', 'SIZES', 'MAILS'],
    ['MODEM', 'MANGA', 'AWARD', 'MEDIA'],
    ['MACRO', 'OMEGA', 'ABOVE', 'MANGA'],
    ['MAMBO', 'ORDER', 'ROOMS', 'MAYOR'],
    ['METRO', 'OTHER', 'ROOTS', 'METER'],
    ['MICRO', 'OUTER', 'ROSES', 'MINOR'],
    ['MAJOR', 'RESET', 'TURBO', 'MEANT'],
    ['MAKER', 'RIGHT', 'THEIR', 'MERIT'],
    ['MANOR', 'ROBOT', 'TIGER', 'MIGHT'],
    ['MAILS', 'SONIC', 'COULD', 'MUSIC'],
    ['MEANT', 'TRUTH', 'HAIRY', 'MOUTH'],
    ['MERIT', 'TOTAL', 'LASER', 'MEDAL'],
    ['MIGHT', 'TRAIL', 'LATER', 'METAL'],
    ['MOUNT', 'TRIAL', 'LAYER', 'MODEL'],
    ['NAVAL', 'LANDS', 'SKINS', 'NAILS'],
    ['NOVEL', 'LANES', 'SLOTS', 'NAMES'],
    ['NIGHT', 'TONER', 'RULES', 'NEVER'],
    ['NASTY', 'YIELD', 'DIRTY', 'NAKED'],
    ['OMEGA', 'ACTOR', 'RESET', 'OCCUR'],
    ['OPERA', 'AFTER', 'RIGHT', 'OFFER'],
    ['OASIS', 'SCUBA', 'ABUSE', 'OMEGA'],
    ['OPENS', 'SIGMA', 'ACUTE', 'OPERA'],
    ['ORBIT', 'TOWER', 'ROBOT', 'OLDER'],
    ['OUGHT', 'TUMOR', 'RENEW', 'ORDER'],
    ['PASTA', 'ANGEL', 'LIVER', 'PANEL'],
    ['PIZZA', 'APRIL', 'LOVER', 'PEARL'],
    ['PLAZA', 'AWFUL', 'LOWER', 'PIXEL'],
    ['PANIC', 'CHIEF', 'FIXED', 'PROOF'],
    ['PROOF', 'FIFTH', 'HANDY', 'PATCH'],
    ['PANEL', 'LEADS', 'SOCKS', 'PACKS'],
    ['PEARL', 'LIKES', 'SONGS', 'PAGES'],
    ['PIXEL', 'LINES', 'SORTS', 'PAIRS'],
    ['PATIO', 'OPERA', 'ADOBE', 'PASTA'],
    ['PHOTO', 'OWNER', 'RELAX', 'PAPER'],
    ['PIANO', 'OASIS', 'SOULS', 'PANTS'],
    ['PROMO', 'OPENS', 'SPIES', 'PARKS'],
    ['PAINT', 'TOPIC', 'CROWD', 'PANIC'],
    ['PILOT', 'TUNER', 'REMIX', 'PETER'],
    ['PLANT', 'TOWNS', 'SPOTS', 'PARTS'],
    ['POINT', 'TREES', 'STARS', 'PATHS'],
    ['PRINT', 'TRIES', 'STATS', 'PEERS'],
    ['REHAB', 'BATCH', 'HAPPY', 'RANCH'],
    ['REBEL', 'LINKS', 'STEPS', 'RACES'],
    ['ROYAL', 'LIONS', 'STOPS', 'RACKS'],
    ['RURAL', 'LISTS', 'SUCKS', 'RANKS'],
    ['REALM', 'MONTH', 'HEAVY', 'REACH'],
    ['RADIO', 'ORBIT', 'TIMER', 'RESET'],
    ['RATIO', 'OUGHT', 'TONER', 'RIGHT'],
    ['RACES', 'SCREW', 'WEIRD', 'RENEW'],
    ['RESET', 'THUMB', 'BASED', 'REHAB'],
    ['RIGHT', 'TRIPS', 'SUITS', 'RATES'],
    ['ROBOT', 'TUBES', 'SWISS', 'READS'],
    ['RENEW', 'WATCH', 'HOBBY', 'ROUGH'],
    ['SANTA', 'AGING', 'GNOME', 'SWING'],
    ['SCUBA', 'ALARM', 'MAPLE', 'SERUM'],
    ['SIGMA', 'ALBUM', 'MAYBE', 'SPERM'],
    ['SONIC', 'CLIFF', 'FLOOD', 'SHELF'],
    ['SHELF', 'FLASH', 'HONEY', 'SARAH'],
    ['STAFF', 'FATAL', 'LAKES', 'SHALL'],
    ['STUFF', 'FINAL', 'LAMPS', 'SHELL'],
    ['SWING', 'GONNA', 'AGREE', 'SANTA'],
    ['SHALL', 'LIVES', 'SAINT', 'SALES'],
    ['SHELL', 'LOADS', 'SCOUT', 'SAVES'],
    ['SKILL', 'LOANS', 'SHAFT', 'SEATS'],
    ['SMALL', 'LOCKS', 'SHEET', 'SEEDS'],
    ['SMELL', 'LOGOS', 'SHIFT', 'SEEKS'],
    ['SPELL', 'LOOKS', 'SHIRT', 'SEEMS'],
    ['STEAL', 'LOOPS', 'SHOOT', 'SELLS'],
    ['STEEL', 'LOTUS', 'SHORT', 'SENDS'],
    ['STILL', 'LOVES', 'SIGHT', 'SHIPS'],
    ['SERUM', 'MEDIA', 'ALIKE', 'SCUBA'],
    ['SPERM', 'MUSIC', 'CABLE', 'SONIC'],
    ['STEAM', 'MEDAL', 'LANDS', 'SKILL'],
    ['STORM', 'METAL', 'LANES', 'SMALL'],
    ['SCOOP', 'PIZZA', 'ALIVE', 'SIGMA'],
    ['SETUP', 'PANEL', 'LEADS', 'SMELL'],
    ['SHARP', 'PEARL', 'LIKES', 'SPELL'],
    ['SHEEP', 'PIXEL', 'LINES', 'STEAL'],
    ['SLEEP', 'PAPER', 'RALLY', 'SAFER'],
    ['STAMP', 'PETER', 'READY', 'SAVER'],
    ['STRAP', 'POKER', 'RELAY', 'SHEER'],
    ['STRIP', 'POLAR', 'REPLY', 'SOLAR'],
    ['SAFER', 'RENEW', 'WIRED', 'SCREW'],
    ['SALES', 'STUFF', 'FLUID', 'STAFF'],
    ['SAVES', 'SHARP', 'PLAZA', 'SCOOP'],
    ['SEATS', 'SHEEP', 'PANIC', 'SETUP'],
    ['SEEDS', 'SLEEP', 'POUND', 'SHARP'],
    ['SEEKS', 'STAMP', 'PROUD', 'SHEEP'],
    ['SEEMS', 'STRAP', 'PASTE', 'SLEEP'],
    ['SELLS', 'STRIP', 'PEACE', 'STAMP'],
    ['SAINT', 'TUNES', 'SKIRT', 'SHOES'],
    ['SCOUT', 'TURNS', 'SMART', 'SHOPS'],
    ['SHAFT', 'TWINS', 'SPENT', 'SHOTS'],
    ['SHEET', 'TYPES', 'SPLIT', 'SHOWS'],
    ['SCREW', 'WHEEL', 'LINKS', 'STEEL'],
    ['THUMB', 'BEING', 'GRACE', 'THING'],
    ['TOPIC', 'CLIMB', 'BLEND', 'THUMB'],
    ['TOXIC', 'CAMEL', 'LIONS', 'TOTAL'],
    ['THING', 'GAMES', 'SPORT', 'TAKES'],
    ['THONG', 'GATES', 'START', 'TALES'],
    ['TOTAL', 'LEAST', 'TOWER', 'THEFT'],
    ['TRAIL', 'LIGHT', 'TUMOR', 'TIGHT'],
    ['TRIAL', 'LIMIT', 'TUNER', 'TRACT'],
    ['THEFT', 'TOXIC', 'CACHE', 'TOPIC'],
    ['THROW', 'WRONG', 'GRADE', 'THONG'],
    ['ULTRA', 'ALONG', 'GRAVE', 'USING'],
    ['USING', 'GOTTA', 'ALONE', 'ULTRA'],
    ['VILLA', 'AUDIO', 'OCEAN', 'VIDEO'],
    ['VISTA', 'ACRES', 'SWEET', 'VIEWS'],
    ['WANNA', 'AMONG', 'GROVE', 'WRONG'],
    ['WRONG', 'GENES', 'SWIFT', 'WAGES'],
    ['YOUNG', 'GIFTS', 'SCREW', 'YARDS'],
];

// Function to select a random word set
function getRandomWordSet() {
    const randomIndex = Math.floor(Math.random() * wordSets.length);
    return wordSets[randomIndex];
}

// Function to create letter tiles (12 middle letters) and corner tiles (4 unique edge letters)
function createLetterTiles(words) {
    if (words.length !== 4 || !words.every(word => word.length === 5)) {
        throw new Error("Invalid input: Expected four five-letter words");
    }

    //construct 2D answer array
    let answerArray = new Array(5).fill(null).map(() => new Array(5).fill(null));
    // Fill the first and last row with the first and third words
    answerArray[0] = words[0].split('');
    answerArray[4] = words[2].split('');

    // Fill the first and last column with the second and last words
    for (let i = 1; i < 4; i++) {
        answerArray[i][0] = words[3][(i + 1) - 1];
        answerArray[i][4] = words[1][(i + 1) - 1];
    }




    // Extract letters for corner tiles

    const firstLetterOfFirstWord = words[0][0];
    const lastLetterOfFirstWord = words[0][words[0].length - 1];
    const firstLetterOfThirdWord = words[2][0];
    const lastLetterOfThirdWord = words[2][words[2].length - 1];
    const cornerTiles = [firstLetterOfFirstWord, lastLetterOfFirstWord, firstLetterOfThirdWord, lastLetterOfThirdWord];


    // Extract the middle three letters of each word
    let middleLetters = words.map(word => word.substring(1, word.length - 1)).join('');

    // Shuffle the middle letters
    middleLetters = middleLetters.split('');
    for (let i = middleLetters.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [middleLetters[i], middleLetters[j]] = [middleLetters[j], middleLetters[i]];
    }

    //reveal three random letters to player
    let revealedLetters = middleLetters.slice(-3);
    middleLetters = middleLetters.slice(0, -3);

    // Function to find the indices of a letter in the 2D answerArray, excluding corner tiles
    function findLetterIndices(letter, array2D, excludePositions = []) {
        let positions = [];

        for (let i = 0; i < array2D.length; i++) {
            for (let j = 0; j < array2D[i].length; j++) {
                // Skip the corner tiles and already used positions
                if ((i === 0 || i === 4) && (j === 0 || j === 4) || excludePositions.some(pos => pos[0] === i && pos[1] === j)) {
                    continue;
                }
                if (array2D[i][j] === letter) {
                    positions.push([i, j]);
                }
            }
        }

        return positions;
    }

    let revealedLetterPositions = [];

    revealedLetters.forEach(letter => {
        let positions = findLetterIndices(letter, answerArray, revealedLetterPositions);
        if (positions.length > 0) {
            // Take the first unused position for this letter
            revealedLetterPositions.push(positions[0]);
        }
    });

    // Return the shuffled middle letters and the unique corner tiles
    return { letterTiles: middleLetters.join(''), cornerTiles: Array.from(cornerTiles), answerArray: Array.from(answerArray), revealedLetters: Array.from(revealedLetters), revealedLetterPositions: Array.from(revealedLetterPositions) };
}

// Route for getting daily words, letter tiles, and corner tiles
router.get('/daily-words', (req, res) => {
    try {
        const words = getRandomWordSet();
        const { letterTiles, cornerTiles, answerArray, revealedLetters, revealedLetterPositions } = createLetterTiles(words);
        res.json({ words, letterTiles, cornerTiles, answerArray, revealedLetters, revealedLetterPositions });
    } catch (error) {
        res.status(500).send(error.message);
    }
});

module.exports = router;
